name: srs
channels:
  - defaults
#  - mlsg
dependencies:
  - configparser
  - numpy
  - lxml
  - nltk
  - scipy
  - sklearn
  - matplotlib
  - flask
  - pandas
  - bokeh
  - vaderSentiment
  - requests
  - python-amazon-simple-product-api
  - bs4
  - fake_useragent
  - xmltodict
  - word2vec
